# This file is managed by 'repo_helper'. Don't edit it directly.
---
name: Linux Tests

on:
  push:
  pull_request:
    branches: ["master"]

jobs:
  tests:
    name: "Python ${{ matrix.python-version }}"
    runs-on: "ubuntu-18.04"
    env:
      USING_COVERAGE: '3.6,3.7,3.8,pypy3,3.9'
    if: contains(github.event.head_commit.message, '[skip ci]') == false

    strategy:
      fail-fast: False
      matrix:
        python-version: ["3.6","3.7","3.8","pypy3","3.9"]

    steps:
      - name: Checkout 🛎️
        uses: "actions/checkout@v2"
      - name: Setup Python 🐍
        uses: "actions/setup-python@v2"
        with:
          python-version: "${{ matrix.python-version }}"
      - name: Install dependencies 🔧
        run: |
          python -VV
          python -m site
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install --upgrade tox tox-gh-actions virtualenv
          python -m pip install --upgrade coverage_pyver_pragma

      - name: "Run Tests for Python ${{ matrix.python-version }}"
        run: "python -m tox"

      - name: "Upload Coverage"
        uses: actions/upload-artifact@v2
        with:
          name: "coverage-${{ matrix.python-version }}"
          path: .coverage


  Coverage:
    needs: tests
    runs-on: "ubuntu-18.04"
    steps:
      - name: Checkout 🛎️
        uses: "actions/checkout@v2"

      - name: Setup Python 🐍
        uses: "actions/setup-python@v2"
        with:
          python-version: 3.8

      - name: Install dependencies 🔧
        run: |
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install --upgrade coveralls coverage_pyver_pragma

      - name: "Download Coverage"
        uses: actions/download-artifact@v2
        with:
          path: coverage

      - name: Display structure of downloaded files
        run: ls -R
        working-directory: coverage

      - name: Combine Coverage
        run: |
          shopt -s globstar
          python -m coverage combine coverage/**/.coverage

      - name: "Upload Combined Coverage Aretfact"
        uses: actions/upload-artifact@v2
        with:
          name: "combined-coverage"
          path: .coverage

      - name: "Upload Combined Coverage to Coveralls"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          coveralls

  Deploy:
    needs: tests

    runs-on: "ubuntu-18.04"
    steps:
      - name: Checkout 🛎️
        uses: "actions/checkout@v2"

      - name: Setup Python 🐍
        uses: "actions/setup-python@v2"
        with:
          python-version: 3.8

      - name: Install dependencies 🔧
        run: |
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install --upgrade tox

      - name: Build source distribution 📦
        run: |
          tox -e build
          rm dist/*.whl

      - name: Upload distribution 📦 to PyPI
        if: startsWith(github.ref, 'refs/tags/')
        uses: pypa/gh-action-pypi-publish@master
        with:
          user: __token__
          password: ${{ secrets.pypi_password }}
          skip_existing: true



  Conda:
    needs: deploy
    runs-on: "ubuntu-18.04"
    steps:
      - name: Checkout 🛎️
        uses: "actions/checkout@v2"

      - name: Install dependencies 🔧
        run: |
          wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
          bash miniconda.sh -b -p $HOME/miniconda
          chmod +x .ci/actions_deploy_conda.sh

      - name: Build and deploy 📦
        run: |
          bash .ci/travis_deploy_conda.sh
        env:
          ANACONDA_TOKEN: ${{ secrets.ANACONDA_TOKEN }}
