# This file is managed by 'repo_helper'. Don't edit it directly.
---
name: Windows Tests 2

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  tests:
    name: "Python ${{ matrix.python-version }}"
    runs-on: "windows-2019"
    env:
      USING_COVERAGE: '3.6,3.7,3.8,pypy3'

    strategy:
      fail-fast: False
      matrix:
        python-version: ["3.6","3.7","3.8","pypy3"]


    steps:
      - name: Setup Python 🐍
        uses: "actions/setup-python@v2"
        with:
          python-version: "${{ matrix.python-version }}"
      - name: Install dependencies 🔧
        run: |
          python -VV
          python -m site
          python -c "import setuptools; print(setuptols.__version__)"
          python -c "import os, sys, distutils; print(os.path.join(os.path.dirname(sys.modules['distutils'].__file__), 'distutils.cfg'))"
          python -c "import os, sys, distutils; from distutils.dist import Distribution; print(Distribution().find_config_files())"
          python -m pip install --upgrade setuptools wheel
          python -m pip install --upgrade tox tox-gh-actions
      - name: Checkout 🛎️
        uses: "actions/checkout@v2"
      - name: "Run Tests for Python ${{ matrix.python-version }}"
        run: "python -m tox"
